//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Hotel
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Анкета К.
    /// </summary>
    // *** Start programmer edit section *** (АнкетаК CustomAttributes)

    // *** End programmer edit section *** (АнкетаК CustomAttributes)
    [AutoAltered()]
    [Caption("Анкета К")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("АнкетаКE", new string[] {
            "НомерК as \'Номер К\'",
            "Прибытие as \'Прибытие\'",
            "Убытие as \'Убытие\'",
            "Админ as \'Админ\'",
            "Персонал as \'Персонал\'"})]
    [MasterViewDefineAttribute("АнкетаКE", "Админ", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "")]
    [MasterViewDefineAttribute("АнкетаКE", "Персонал", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "")]
    [View("АнкетаКL", new string[] {
            "НомерК as \'Номер К\'",
            "Прибытие as \'Прибытие\'",
            "Убытие as \'Убытие\'"})]
    public class АнкетаК : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомерК;
        
        private System.DateTime fПрибытие;
        
        private System.DateTime fУбытие;
        
        private IIS.Hotel.Админ fАдмин;
        
        private IIS.Hotel.Персонал fПерсонал;
        
        // *** Start programmer edit section *** (АнкетаК CustomMembers)

        // *** End programmer edit section *** (АнкетаК CustomMembers)

        
        /// <summary>
        /// НомерК.
        /// </summary>
        // *** Start programmer edit section *** (АнкетаК.НомерК CustomAttributes)

        // *** End programmer edit section *** (АнкетаК.НомерК CustomAttributes)
        public virtual int НомерК
        {
            get
            {
                // *** Start programmer edit section *** (АнкетаК.НомерК Get start)

                // *** End programmer edit section *** (АнкетаК.НомерК Get start)
                int result = this.fНомерК;
                // *** Start programmer edit section *** (АнкетаК.НомерК Get end)

                // *** End programmer edit section *** (АнкетаК.НомерК Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (АнкетаК.НомерК Set start)

                // *** End programmer edit section *** (АнкетаК.НомерК Set start)
                this.fНомерК = value;
                // *** Start programmer edit section *** (АнкетаК.НомерК Set end)

                // *** End programmer edit section *** (АнкетаК.НомерК Set end)
            }
        }
        
        /// <summary>
        /// Прибытие.
        /// </summary>
        // *** Start programmer edit section *** (АнкетаК.Прибытие CustomAttributes)

        // *** End programmer edit section *** (АнкетаК.Прибытие CustomAttributes)
        public virtual System.DateTime Прибытие
        {
            get
            {
                // *** Start programmer edit section *** (АнкетаК.Прибытие Get start)

                // *** End programmer edit section *** (АнкетаК.Прибытие Get start)
                System.DateTime result = this.fПрибытие;
                // *** Start programmer edit section *** (АнкетаК.Прибытие Get end)

                // *** End programmer edit section *** (АнкетаК.Прибытие Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (АнкетаК.Прибытие Set start)

                // *** End programmer edit section *** (АнкетаК.Прибытие Set start)
                this.fПрибытие = value;
                // *** Start programmer edit section *** (АнкетаК.Прибытие Set end)

                // *** End programmer edit section *** (АнкетаК.Прибытие Set end)
            }
        }
        
        /// <summary>
        /// Убытие.
        /// </summary>
        // *** Start programmer edit section *** (АнкетаК.Убытие CustomAttributes)

        // *** End programmer edit section *** (АнкетаК.Убытие CustomAttributes)
        public virtual System.DateTime Убытие
        {
            get
            {
                // *** Start programmer edit section *** (АнкетаК.Убытие Get start)

                // *** End programmer edit section *** (АнкетаК.Убытие Get start)
                System.DateTime result = this.fУбытие;
                // *** Start programmer edit section *** (АнкетаК.Убытие Get end)

                // *** End programmer edit section *** (АнкетаК.Убытие Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (АнкетаК.Убытие Set start)

                // *** End programmer edit section *** (АнкетаК.Убытие Set start)
                this.fУбытие = value;
                // *** Start programmer edit section *** (АнкетаК.Убытие Set end)

                // *** End programmer edit section *** (АнкетаК.Убытие Set end)
            }
        }
        
        /// <summary>
        /// Анкета К.
        /// </summary>
        // *** Start programmer edit section *** (АнкетаК.Админ CustomAttributes)

        // *** End programmer edit section *** (АнкетаК.Админ CustomAttributes)
        [PropertyStorage(new string[] {
                "Админ"})]
        [NotNull()]
        public virtual IIS.Hotel.Админ Админ
        {
            get
            {
                // *** Start programmer edit section *** (АнкетаК.Админ Get start)

                // *** End programmer edit section *** (АнкетаК.Админ Get start)
                IIS.Hotel.Админ result = this.fАдмин;
                // *** Start programmer edit section *** (АнкетаК.Админ Get end)

                // *** End programmer edit section *** (АнкетаК.Админ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (АнкетаК.Админ Set start)

                // *** End programmer edit section *** (АнкетаК.Админ Set start)
                this.fАдмин = value;
                // *** Start programmer edit section *** (АнкетаК.Админ Set end)

                // *** End programmer edit section *** (АнкетаК.Админ Set end)
            }
        }
        
        /// <summary>
        /// Анкета К.
        /// </summary>
        // *** Start programmer edit section *** (АнкетаК.Персонал CustomAttributes)

        // *** End programmer edit section *** (АнкетаК.Персонал CustomAttributes)
        [PropertyStorage(new string[] {
                "Персонал"})]
        [NotNull()]
        public virtual IIS.Hotel.Персонал Персонал
        {
            get
            {
                // *** Start programmer edit section *** (АнкетаК.Персонал Get start)

                // *** End programmer edit section *** (АнкетаК.Персонал Get start)
                IIS.Hotel.Персонал result = this.fПерсонал;
                // *** Start programmer edit section *** (АнкетаК.Персонал Get end)

                // *** End programmer edit section *** (АнкетаК.Персонал Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (АнкетаК.Персонал Set start)

                // *** End programmer edit section *** (АнкетаК.Персонал Set start)
                this.fПерсонал = value;
                // *** Start programmer edit section *** (АнкетаК.Персонал Set end)

                // *** End programmer edit section *** (АнкетаК.Персонал Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "АнкетаКE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View АнкетаКE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("АнкетаКE", typeof(IIS.Hotel.АнкетаК));
                }
            }
            
            /// <summary>
            /// "АнкетаКL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View АнкетаКL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("АнкетаКL", typeof(IIS.Hotel.АнкетаК));
                }
            }
        }
    }
}
