//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Hotel
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// АОПИ.
    /// </summary>
    // *** Start programmer edit section *** (АОПИ CustomAttributes)

    // *** End programmer edit section *** (АОПИ CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("АОПИE", new string[] {
            "НомерКомнаты as \'Номер комнаты\'",
            "Персонал as \'Персонал\'",
            "Админ as \'Админ\'"})]
    [AssociatedDetailViewAttribute("АОПИE", "ТЧ1", "ТЧ1E", true, "", "Т ч1", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("АОПИE", "Персонал", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "")]
    [MasterViewDefineAttribute("АОПИE", "Админ", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "")]
    [View("АОПИL", new string[] {
            "НомерКомнаты as \'Номер комнаты\'"})]
    public class АОПИ : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомерКомнаты;
        
        private IIS.Hotel.Персонал fПерсонал;
        
        private IIS.Hotel.Админ fАдмин;
        
        private IIS.Hotel.DetailArrayOfТЧ1 fТЧ1;
        
        // *** Start programmer edit section *** (АОПИ CustomMembers)

        // *** End programmer edit section *** (АОПИ CustomMembers)

        
        /// <summary>
        /// НомерКомнаты.
        /// </summary>
        // *** Start programmer edit section *** (АОПИ.НомерКомнаты CustomAttributes)

        // *** End programmer edit section *** (АОПИ.НомерКомнаты CustomAttributes)
        public virtual int НомерКомнаты
        {
            get
            {
                // *** Start programmer edit section *** (АОПИ.НомерКомнаты Get start)

                // *** End programmer edit section *** (АОПИ.НомерКомнаты Get start)
                int result = this.fНомерКомнаты;
                // *** Start programmer edit section *** (АОПИ.НомерКомнаты Get end)

                // *** End programmer edit section *** (АОПИ.НомерКомнаты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (АОПИ.НомерКомнаты Set start)

                // *** End programmer edit section *** (АОПИ.НомерКомнаты Set start)
                this.fНомерКомнаты = value;
                // *** Start programmer edit section *** (АОПИ.НомерКомнаты Set end)

                // *** End programmer edit section *** (АОПИ.НомерКомнаты Set end)
            }
        }
        
        /// <summary>
        /// АОПИ.
        /// </summary>
        // *** Start programmer edit section *** (АОПИ.Админ CustomAttributes)

        // *** End programmer edit section *** (АОПИ.Админ CustomAttributes)
        [PropertyStorage(new string[] {
                "Админ"})]
        [NotNull()]
        public virtual IIS.Hotel.Админ Админ
        {
            get
            {
                // *** Start programmer edit section *** (АОПИ.Админ Get start)

                // *** End programmer edit section *** (АОПИ.Админ Get start)
                IIS.Hotel.Админ result = this.fАдмин;
                // *** Start programmer edit section *** (АОПИ.Админ Get end)

                // *** End programmer edit section *** (АОПИ.Админ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (АОПИ.Админ Set start)

                // *** End programmer edit section *** (АОПИ.Админ Set start)
                this.fАдмин = value;
                // *** Start programmer edit section *** (АОПИ.Админ Set end)

                // *** End programmer edit section *** (АОПИ.Админ Set end)
            }
        }
        
        /// <summary>
        /// АОПИ.
        /// </summary>
        // *** Start programmer edit section *** (АОПИ.Персонал CustomAttributes)

        // *** End programmer edit section *** (АОПИ.Персонал CustomAttributes)
        [PropertyStorage(new string[] {
                "Персонал"})]
        [NotNull()]
        public virtual IIS.Hotel.Персонал Персонал
        {
            get
            {
                // *** Start programmer edit section *** (АОПИ.Персонал Get start)

                // *** End programmer edit section *** (АОПИ.Персонал Get start)
                IIS.Hotel.Персонал result = this.fПерсонал;
                // *** Start programmer edit section *** (АОПИ.Персонал Get end)

                // *** End programmer edit section *** (АОПИ.Персонал Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (АОПИ.Персонал Set start)

                // *** End programmer edit section *** (АОПИ.Персонал Set start)
                this.fПерсонал = value;
                // *** Start programmer edit section *** (АОПИ.Персонал Set end)

                // *** End programmer edit section *** (АОПИ.Персонал Set end)
            }
        }
        
        /// <summary>
        /// АОПИ.
        /// </summary>
        // *** Start programmer edit section *** (АОПИ.ТЧ1 CustomAttributes)

        // *** End programmer edit section *** (АОПИ.ТЧ1 CustomAttributes)
        public virtual IIS.Hotel.DetailArrayOfТЧ1 ТЧ1
        {
            get
            {
                // *** Start programmer edit section *** (АОПИ.ТЧ1 Get start)

                // *** End programmer edit section *** (АОПИ.ТЧ1 Get start)
                if ((this.fТЧ1 == null))
                {
                    this.fТЧ1 = new IIS.Hotel.DetailArrayOfТЧ1(this);
                }
                IIS.Hotel.DetailArrayOfТЧ1 result = this.fТЧ1;
                // *** Start programmer edit section *** (АОПИ.ТЧ1 Get end)

                // *** End programmer edit section *** (АОПИ.ТЧ1 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (АОПИ.ТЧ1 Set start)

                // *** End programmer edit section *** (АОПИ.ТЧ1 Set start)
                this.fТЧ1 = value;
                // *** Start programmer edit section *** (АОПИ.ТЧ1 Set end)

                // *** End programmer edit section *** (АОПИ.ТЧ1 Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "АОПИE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View АОПИE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("АОПИE", typeof(IIS.Hotel.АОПИ));
                }
            }
            
            /// <summary>
            /// "АОПИL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View АОПИL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("АОПИL", typeof(IIS.Hotel.АОПИ));
                }
            }
        }
    }
}
