//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Hotel
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Гостиница.
    /// </summary>
    // *** Start programmer edit section *** (Гостиница CustomAttributes)

    // *** End programmer edit section *** (Гостиница CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ГостиницаE", new string[] {
            "Название as \'Название\'"})]
    [View("ГостиницаL", new string[] {
            "Название as \'Название\'"})]
    public class Гостиница : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазвание;
        
        // *** Start programmer edit section *** (Гостиница CustomMembers)

        // *** End programmer edit section *** (Гостиница CustomMembers)

        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (Гостиница.Название CustomAttributes)

        // *** End programmer edit section *** (Гостиница.Название CustomAttributes)
        [StrLen(255)]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (Гостиница.Название Get start)

                // *** End programmer edit section *** (Гостиница.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (Гостиница.Название Get end)

                // *** End programmer edit section *** (Гостиница.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Гостиница.Название Set start)

                // *** End programmer edit section *** (Гостиница.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (Гостиница.Название Set end)

                // *** End programmer edit section *** (Гостиница.Название Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ГостиницаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ГостиницаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ГостиницаE", typeof(IIS.Hotel.Гостиница));
                }
            }
            
            /// <summary>
            /// "ГостиницаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ГостиницаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ГостиницаL", typeof(IIS.Hotel.Гостиница));
                }
            }
        }
    }
}
