//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Hotel
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Должность.
    /// </summary>
    // *** Start programmer edit section *** (Должность CustomAttributes)

    // *** End programmer edit section *** (Должность CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДолжностьE", new string[] {
            "КодДолжност as \'Код должност\'",
            "Название as \'Название\'"})]
    [View("ДолжностьL", new string[] {
            "КодДолжност as \'Код должност\'",
            "Название as \'Название\'"})]
    public class Должность : ICSSoft.STORMNET.DataObject
    {
        
        private int fКодДолжност;
        
        private string fНазвание;
        
        private IIS.Hotel.ПаспДанные fПаспДанные;
        
        // *** Start programmer edit section *** (Должность CustomMembers)

        // *** End programmer edit section *** (Должность CustomMembers)

        
        /// <summary>
        /// КодДолжност.
        /// </summary>
        // *** Start programmer edit section *** (Должность.КодДолжност CustomAttributes)

        // *** End programmer edit section *** (Должность.КодДолжност CustomAttributes)
        public virtual int КодДолжност
        {
            get
            {
                // *** Start programmer edit section *** (Должность.КодДолжност Get start)

                // *** End programmer edit section *** (Должность.КодДолжност Get start)
                int result = this.fКодДолжност;
                // *** Start programmer edit section *** (Должность.КодДолжност Get end)

                // *** End programmer edit section *** (Должность.КодДолжност Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Должность.КодДолжност Set start)

                // *** End programmer edit section *** (Должность.КодДолжност Set start)
                this.fКодДолжност = value;
                // *** Start programmer edit section *** (Должность.КодДолжност Set end)

                // *** End programmer edit section *** (Должность.КодДолжност Set end)
            }
        }
        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (Должность.Название CustomAttributes)

        // *** End programmer edit section *** (Должность.Название CustomAttributes)
        [StrLen(255)]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (Должность.Название Get start)

                // *** End programmer edit section *** (Должность.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (Должность.Название Get end)

                // *** End programmer edit section *** (Должность.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Должность.Название Set start)

                // *** End programmer edit section *** (Должность.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (Должность.Название Set end)

                // *** End programmer edit section *** (Должность.Название Set end)
            }
        }
        
        /// <summary>
        /// Должность.
        /// </summary>
        // *** Start programmer edit section *** (Должность.ПаспДанные CustomAttributes)

        // *** End programmer edit section *** (Должность.ПаспДанные CustomAttributes)
        [PropertyStorage(new string[] {
                "ПаспДанные"})]
        [NotNull()]
        public virtual IIS.Hotel.ПаспДанные ПаспДанные
        {
            get
            {
                // *** Start programmer edit section *** (Должность.ПаспДанные Get start)

                // *** End programmer edit section *** (Должность.ПаспДанные Get start)
                IIS.Hotel.ПаспДанные result = this.fПаспДанные;
                // *** Start programmer edit section *** (Должность.ПаспДанные Get end)

                // *** End programmer edit section *** (Должность.ПаспДанные Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Должность.ПаспДанные Set start)

                // *** End programmer edit section *** (Должность.ПаспДанные Set start)
                this.fПаспДанные = value;
                // *** Start programmer edit section *** (Должность.ПаспДанные Set end)

                // *** End programmer edit section *** (Должность.ПаспДанные Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДолжностьE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДолжностьE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДолжностьE", typeof(IIS.Hotel.Должность));
                }
            }
            
            /// <summary>
            /// "ДолжностьL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДолжностьL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДолжностьL", typeof(IIS.Hotel.Должность));
                }
            }
        }
    }
}
