//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Hotel
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ЖРИГ.
    /// </summary>
    // *** Start programmer edit section *** (ЖРИГ CustomAttributes)

    // *** End programmer edit section *** (ЖРИГ CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЖРИГE", new string[] {
            "НомерЖурн as \'Номер журн\'",
            "Дата as \'Дата\'",
            "Админ as \'Админ\'"})]
    [AssociatedDetailViewAttribute("ЖРИГE", "ТЧ2", "ТЧ2E", true, "", "Т ч2", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ЖРИГE", "Админ", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "")]
    [View("ЖРИГL", new string[] {
            "НомерЖурн as \'Номер журн\'",
            "Дата as \'Дата\'"})]
    public class ЖРИГ : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомерЖурн;
        
        private System.DateTime fДата;
        
        private IIS.Hotel.Админ fАдмин;
        
        private IIS.Hotel.DetailArrayOfТЧ2 fТЧ2;
        
        // *** Start programmer edit section *** (ЖРИГ CustomMembers)

        // *** End programmer edit section *** (ЖРИГ CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ЖРИГ.Дата CustomAttributes)

        // *** End programmer edit section *** (ЖРИГ.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ЖРИГ.Дата Get start)

                // *** End programmer edit section *** (ЖРИГ.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ЖРИГ.Дата Get end)

                // *** End programmer edit section *** (ЖРИГ.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЖРИГ.Дата Set start)

                // *** End programmer edit section *** (ЖРИГ.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ЖРИГ.Дата Set end)

                // *** End programmer edit section *** (ЖРИГ.Дата Set end)
            }
        }
        
        /// <summary>
        /// НомерЖурн.
        /// </summary>
        // *** Start programmer edit section *** (ЖРИГ.НомерЖурн CustomAttributes)

        // *** End programmer edit section *** (ЖРИГ.НомерЖурн CustomAttributes)
        public virtual int НомерЖурн
        {
            get
            {
                // *** Start programmer edit section *** (ЖРИГ.НомерЖурн Get start)

                // *** End programmer edit section *** (ЖРИГ.НомерЖурн Get start)
                int result = this.fНомерЖурн;
                // *** Start programmer edit section *** (ЖРИГ.НомерЖурн Get end)

                // *** End programmer edit section *** (ЖРИГ.НомерЖурн Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЖРИГ.НомерЖурн Set start)

                // *** End programmer edit section *** (ЖРИГ.НомерЖурн Set start)
                this.fНомерЖурн = value;
                // *** Start programmer edit section *** (ЖРИГ.НомерЖурн Set end)

                // *** End programmer edit section *** (ЖРИГ.НомерЖурн Set end)
            }
        }
        
        /// <summary>
        /// ЖРИГ.
        /// </summary>
        // *** Start programmer edit section *** (ЖРИГ.Админ CustomAttributes)

        // *** End programmer edit section *** (ЖРИГ.Админ CustomAttributes)
        [PropertyStorage(new string[] {
                "Админ"})]
        [NotNull()]
        public virtual IIS.Hotel.Админ Админ
        {
            get
            {
                // *** Start programmer edit section *** (ЖРИГ.Админ Get start)

                // *** End programmer edit section *** (ЖРИГ.Админ Get start)
                IIS.Hotel.Админ result = this.fАдмин;
                // *** Start programmer edit section *** (ЖРИГ.Админ Get end)

                // *** End programmer edit section *** (ЖРИГ.Админ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЖРИГ.Админ Set start)

                // *** End programmer edit section *** (ЖРИГ.Админ Set start)
                this.fАдмин = value;
                // *** Start programmer edit section *** (ЖРИГ.Админ Set end)

                // *** End programmer edit section *** (ЖРИГ.Админ Set end)
            }
        }
        
        /// <summary>
        /// ЖРИГ.
        /// </summary>
        // *** Start programmer edit section *** (ЖРИГ.ТЧ2 CustomAttributes)

        // *** End programmer edit section *** (ЖРИГ.ТЧ2 CustomAttributes)
        public virtual IIS.Hotel.DetailArrayOfТЧ2 ТЧ2
        {
            get
            {
                // *** Start programmer edit section *** (ЖРИГ.ТЧ2 Get start)

                // *** End programmer edit section *** (ЖРИГ.ТЧ2 Get start)
                if ((this.fТЧ2 == null))
                {
                    this.fТЧ2 = new IIS.Hotel.DetailArrayOfТЧ2(this);
                }
                IIS.Hotel.DetailArrayOfТЧ2 result = this.fТЧ2;
                // *** Start programmer edit section *** (ЖРИГ.ТЧ2 Get end)

                // *** End programmer edit section *** (ЖРИГ.ТЧ2 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЖРИГ.ТЧ2 Set start)

                // *** End programmer edit section *** (ЖРИГ.ТЧ2 Set start)
                this.fТЧ2 = value;
                // *** Start programmer edit section *** (ЖРИГ.ТЧ2 Set end)

                // *** End programmer edit section *** (ЖРИГ.ТЧ2 Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЖРИГE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЖРИГE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЖРИГE", typeof(IIS.Hotel.ЖРИГ));
                }
            }
            
            /// <summary>
            /// "ЖРИГL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЖРИГL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЖРИГL", typeof(IIS.Hotel.ЖРИГ));
                }
            }
        }
    }
}
