//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Hotel
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Пасп данные.
    /// </summary>
    // *** Start programmer edit section *** (ПаспДанные CustomAttributes)

    // *** End programmer edit section *** (ПаспДанные CustomAttributes)
    [AutoAltered()]
    [Caption("Пасп данные")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПаспДанныеE", new string[] {
            "ФИО as \'ФИО\'",
            "ДатаРожд as \'Дата рожд\'",
            "СерияПаспорта as \'Серия паспорта\'",
            "НомерПаспорта as \'Номер паспорта\'",
            "Гражданство as \'Гражданство\'",
            "ИнГражд as \'Ин гражд\'"})]
    [View("ПаспДанныеL", new string[] {
            "ФИО as \'ФИО\'",
            "ДатаРожд as \'Дата рожд\'",
            "СерияПаспорта as \'Серия паспорта\'",
            "НомерПаспорта as \'Номер паспорта\'",
            "Гражданство as \'Гражданство\'",
            "ИнГражд as \'Ин гражд\'"})]
    public class ПаспДанные : ICSSoft.STORMNET.DataObject
    {
        
        private string fФИО;
        
        private System.DateTime fДатаРожд;
        
        private int fСерияПаспорта;
        
        private int fНомерПаспорта;
        
        private string fГражданство;
        
        private bool fИнГражд;
        
        // *** Start programmer edit section *** (ПаспДанные CustomMembers)

        // *** End programmer edit section *** (ПаспДанные CustomMembers)

        
        /// <summary>
        /// Гражданство.
        /// </summary>
        // *** Start programmer edit section *** (ПаспДанные.Гражданство CustomAttributes)

        // *** End programmer edit section *** (ПаспДанные.Гражданство CustomAttributes)
        [StrLen(255)]
        public virtual string Гражданство
        {
            get
            {
                // *** Start programmer edit section *** (ПаспДанные.Гражданство Get start)

                // *** End programmer edit section *** (ПаспДанные.Гражданство Get start)
                string result = this.fГражданство;
                // *** Start programmer edit section *** (ПаспДанные.Гражданство Get end)

                // *** End programmer edit section *** (ПаспДанные.Гражданство Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПаспДанные.Гражданство Set start)

                // *** End programmer edit section *** (ПаспДанные.Гражданство Set start)
                this.fГражданство = value;
                // *** Start programmer edit section *** (ПаспДанные.Гражданство Set end)

                // *** End programmer edit section *** (ПаспДанные.Гражданство Set end)
            }
        }
        
        /// <summary>
        /// ДатаРожд.
        /// </summary>
        // *** Start programmer edit section *** (ПаспДанные.ДатаРожд CustomAttributes)

        // *** End programmer edit section *** (ПаспДанные.ДатаРожд CustomAttributes)
        public virtual System.DateTime ДатаРожд
        {
            get
            {
                // *** Start programmer edit section *** (ПаспДанные.ДатаРожд Get start)

                // *** End programmer edit section *** (ПаспДанные.ДатаРожд Get start)
                System.DateTime result = this.fДатаРожд;
                // *** Start programmer edit section *** (ПаспДанные.ДатаРожд Get end)

                // *** End programmer edit section *** (ПаспДанные.ДатаРожд Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПаспДанные.ДатаРожд Set start)

                // *** End programmer edit section *** (ПаспДанные.ДатаРожд Set start)
                this.fДатаРожд = value;
                // *** Start programmer edit section *** (ПаспДанные.ДатаРожд Set end)

                // *** End programmer edit section *** (ПаспДанные.ДатаРожд Set end)
            }
        }
        
        /// <summary>
        /// ИнГражд.
        /// </summary>
        // *** Start programmer edit section *** (ПаспДанные.ИнГражд CustomAttributes)

        // *** End programmer edit section *** (ПаспДанные.ИнГражд CustomAttributes)
        public virtual bool ИнГражд
        {
            get
            {
                // *** Start programmer edit section *** (ПаспДанные.ИнГражд Get start)

                // *** End programmer edit section *** (ПаспДанные.ИнГражд Get start)
                bool result = this.fИнГражд;
                // *** Start programmer edit section *** (ПаспДанные.ИнГражд Get end)

                // *** End programmer edit section *** (ПаспДанные.ИнГражд Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПаспДанные.ИнГражд Set start)

                // *** End programmer edit section *** (ПаспДанные.ИнГражд Set start)
                this.fИнГражд = value;
                // *** Start programmer edit section *** (ПаспДанные.ИнГражд Set end)

                // *** End programmer edit section *** (ПаспДанные.ИнГражд Set end)
            }
        }
        
        /// <summary>
        /// НомерПаспорта.
        /// </summary>
        // *** Start programmer edit section *** (ПаспДанные.НомерПаспорта CustomAttributes)

        // *** End programmer edit section *** (ПаспДанные.НомерПаспорта CustomAttributes)
        public virtual int НомерПаспорта
        {
            get
            {
                // *** Start programmer edit section *** (ПаспДанные.НомерПаспорта Get start)

                // *** End programmer edit section *** (ПаспДанные.НомерПаспорта Get start)
                int result = this.fНомерПаспорта;
                // *** Start programmer edit section *** (ПаспДанные.НомерПаспорта Get end)

                // *** End programmer edit section *** (ПаспДанные.НомерПаспорта Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПаспДанные.НомерПаспорта Set start)

                // *** End programmer edit section *** (ПаспДанные.НомерПаспорта Set start)
                this.fНомерПаспорта = value;
                // *** Start programmer edit section *** (ПаспДанные.НомерПаспорта Set end)

                // *** End programmer edit section *** (ПаспДанные.НомерПаспорта Set end)
            }
        }
        
        /// <summary>
        /// СерияПаспорта.
        /// </summary>
        // *** Start programmer edit section *** (ПаспДанные.СерияПаспорта CustomAttributes)

        // *** End programmer edit section *** (ПаспДанные.СерияПаспорта CustomAttributes)
        public virtual int СерияПаспорта
        {
            get
            {
                // *** Start programmer edit section *** (ПаспДанные.СерияПаспорта Get start)

                // *** End programmer edit section *** (ПаспДанные.СерияПаспорта Get start)
                int result = this.fСерияПаспорта;
                // *** Start programmer edit section *** (ПаспДанные.СерияПаспорта Get end)

                // *** End programmer edit section *** (ПаспДанные.СерияПаспорта Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПаспДанные.СерияПаспорта Set start)

                // *** End programmer edit section *** (ПаспДанные.СерияПаспорта Set start)
                this.fСерияПаспорта = value;
                // *** Start programmer edit section *** (ПаспДанные.СерияПаспорта Set end)

                // *** End programmer edit section *** (ПаспДанные.СерияПаспорта Set end)
            }
        }
        
        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (ПаспДанные.ФИО CustomAttributes)

        // *** End programmer edit section *** (ПаспДанные.ФИО CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО
        {
            get
            {
                // *** Start programmer edit section *** (ПаспДанные.ФИО Get start)

                // *** End programmer edit section *** (ПаспДанные.ФИО Get start)
                string result = this.fФИО;
                // *** Start programmer edit section *** (ПаспДанные.ФИО Get end)

                // *** End programmer edit section *** (ПаспДанные.ФИО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПаспДанные.ФИО Set start)

                // *** End programmer edit section *** (ПаспДанные.ФИО Set start)
                this.fФИО = value;
                // *** Start programmer edit section *** (ПаспДанные.ФИО Set end)

                // *** End programmer edit section *** (ПаспДанные.ФИО Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПаспДанныеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПаспДанныеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПаспДанныеE", typeof(IIS.Hotel.ПаспДанные));
                }
            }
            
            /// <summary>
            /// "ПаспДанныеL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПаспДанныеL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПаспДанныеL", typeof(IIS.Hotel.ПаспДанные));
                }
            }
        }
    }
}
