//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Hotel
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Т ч1.
    /// </summary>
    // *** Start programmer edit section *** (ТЧ1 CustomAttributes)

    // *** End programmer edit section *** (ТЧ1 CustomAttributes)
    [AutoAltered()]
    [Caption("Т ч1")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТЧ1E", new string[] {
            "Имущество as \'Имущество\'",
            "Стоимость as \'Стоимость\'"})]
    public class ТЧ1 : ICSSoft.STORMNET.DataObject
    {
        
        private string fИмущество;
        
        private int fСтоимость;
        
        private IIS.Hotel.АОПИ fАОПИ;
        
        // *** Start programmer edit section *** (ТЧ1 CustomMembers)

        // *** End programmer edit section *** (ТЧ1 CustomMembers)

        
        /// <summary>
        /// Имущество.
        /// </summary>
        // *** Start programmer edit section *** (ТЧ1.Имущество CustomAttributes)

        // *** End programmer edit section *** (ТЧ1.Имущество CustomAttributes)
        [StrLen(255)]
        public virtual string Имущество
        {
            get
            {
                // *** Start programmer edit section *** (ТЧ1.Имущество Get start)

                // *** End programmer edit section *** (ТЧ1.Имущество Get start)
                string result = this.fИмущество;
                // *** Start programmer edit section *** (ТЧ1.Имущество Get end)

                // *** End programmer edit section *** (ТЧ1.Имущество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧ1.Имущество Set start)

                // *** End programmer edit section *** (ТЧ1.Имущество Set start)
                this.fИмущество = value;
                // *** Start programmer edit section *** (ТЧ1.Имущество Set end)

                // *** End programmer edit section *** (ТЧ1.Имущество Set end)
            }
        }
        
        /// <summary>
        /// Стоимость.
        /// </summary>
        // *** Start programmer edit section *** (ТЧ1.Стоимость CustomAttributes)

        // *** End programmer edit section *** (ТЧ1.Стоимость CustomAttributes)
        public virtual int Стоимость
        {
            get
            {
                // *** Start programmer edit section *** (ТЧ1.Стоимость Get start)

                // *** End programmer edit section *** (ТЧ1.Стоимость Get start)
                int result = this.fСтоимость;
                // *** Start programmer edit section *** (ТЧ1.Стоимость Get end)

                // *** End programmer edit section *** (ТЧ1.Стоимость Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧ1.Стоимость Set start)

                // *** End programmer edit section *** (ТЧ1.Стоимость Set start)
                this.fСтоимость = value;
                // *** Start programmer edit section *** (ТЧ1.Стоимость Set end)

                // *** End programmer edit section *** (ТЧ1.Стоимость Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Hotel.АОПИ.
        /// </summary>
        // *** Start programmer edit section *** (ТЧ1.АОПИ CustomAttributes)

        // *** End programmer edit section *** (ТЧ1.АОПИ CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "АОПИ"})]
        public virtual IIS.Hotel.АОПИ АОПИ
        {
            get
            {
                // *** Start programmer edit section *** (ТЧ1.АОПИ Get start)

                // *** End programmer edit section *** (ТЧ1.АОПИ Get start)
                IIS.Hotel.АОПИ result = this.fАОПИ;
                // *** Start programmer edit section *** (ТЧ1.АОПИ Get end)

                // *** End programmer edit section *** (ТЧ1.АОПИ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧ1.АОПИ Set start)

                // *** End programmer edit section *** (ТЧ1.АОПИ Set start)
                this.fАОПИ = value;
                // *** Start programmer edit section *** (ТЧ1.АОПИ Set end)

                // *** End programmer edit section *** (ТЧ1.АОПИ Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТЧ1E" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТЧ1E
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТЧ1E", typeof(IIS.Hotel.ТЧ1));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ТЧ1.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfТЧ1 CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfТЧ1 CustomAttributes)
    public class DetailArrayOfТЧ1 : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Hotel.DetailArrayOfТЧ1 members)

        // *** End programmer edit section *** (IIS.Hotel.DetailArrayOfТЧ1 members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ТЧ1 by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ТЧ1.
        /// </summary>
        public DetailArrayOfТЧ1(IIS.Hotel.АОПИ fАОПИ) : 
                base(typeof(ТЧ1), ((ICSSoft.STORMNET.DataObject)(fАОПИ)))
        {
        }
        
        public IIS.Hotel.ТЧ1 this[int index]
        {
            get
            {
                return ((IIS.Hotel.ТЧ1)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Hotel.ТЧ1 dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
